server:
  port: 8000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # auth
        - id: auth-service
          predicates:
            - Path=/api/auth-service/**
          uri: http://localhost:8081
          filters:
            - RewritePath=/api/auth-service/?(?<segment>.*), /$\{segment}

        # user
        - id: user-service
          predicates:
            - Path=/api/user-service/**
          uri: http://localhost:8082
          filters:
              - RewritePath=/api/user-service/?(?<segment>.*), /$\{segment}

        # pr
        - id: pr-service
          predicates:
            - Path=/api/pr-service/**
          uri: http://localhost:8080
          filters:
            - RewritePath=/api/pr-service/?(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        # rfq
        - id: rfq-service
          predicates:
            - Path=/api/rfq-service/**
          uri: http://localhost:8080
          filters:
            - RewritePath=/api/rfq-service/?(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        # po
        - id: po-service
          predicates:
            - Path=/api/po-service/**
          uri: http://localhost:8080
          filters:
            - RewritePath=/api/po-service/?(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        # scc / mobile
        - id: scc-service
          predicates:
            - Path=/api/scc-service/**
          uri: http://localhost:8080
          filters:
            - RewritePath=/api/scc-service/?(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

# Eureka
eureka:
  instance:
    prefer-ip-address: true
#    ip-address: 13.208.160.27
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.208.124.73:8761/eureka/
    registryFetchIntervalSeconds: 5
